### ISSUE TITLE
error when trying to add the grafana panel

### ISSUE THREAD

**Issue by jlisbz** [andrewchambers/grafana-rrd-datasource#1]
Hi,

Thanks for your grafana rrd solution. I got the rrdsrv running properly, the plugin installed, able to add the datasource in grafana. But could not show any data when adding panel. The query inspector show the error is "unable to parse response json: cannot parse JSON: cannot parse object: cannot find opening '\"\" for object key; unparsed tail: \"about: 'RRDtool xport JSON output',  met....0895027287e+03, 2.0456499615e+02  ]  ]}\" 

I have the rrd (e)port almost the same as yours in the demo video. It has been tested working with rrdsrv too. But not working when adding the grafana panel. 

I don't have much experience for grafana yet so just want to report this to you. Hope you can figure out what happened.

My OSS grafana version is 8.2.1  

Thanks.

**Comment by andrewchambers** [comment]
Are you able to input the query into your instance of rrdsrv directly ? It should be possible to view the json data that is returned so we can check if it is corrupt.

Also I wonder if you have an older version of rrdtool installed.

**Comment by jlisbz** [comment]
Yes, able to query via the rrdsrv directly. The output is a json object with the fields about, meta and data. 

The field data is  an array with all the data inside.

**Comment by andrewchambers** [comment]
My rrdtool version is:

```
RRDtool 1.7.2  Copyright by Tobias Oetiker <tobi@oetiker.ch>
               Compiled May 27 2019 18:48:09
```

Is your version different?

**Comment by jlisbz** [comment]
The rrdtool is 1.4.8, will upgrade and let you know. Thanks.

**Comment by jlisbz** [comment]
I installed rrdtool 1.7.2 and compared the rrdtool xport output and found very small difference between version 1.4.8 and 1.7.2.

Run the rrdsrv with the config option rrdtool_command to be "exec /newpath/rrdtool", tested with the grafana and found it works now.

Thanks a lot.
